### ISSUE TITLE
ClassCastException with Push

### ISSUE THREAD

**Issue by davidsowerby** [mcollovati/vertx-vaadin#14]
Attempting to run Krail on vertx-vaadn:

>New push connection for resource 289d7b40-2c21-4db6-b5b9-6950d3022f48 with transport resource.transport() 
Unhandled exception 
java.lang.ClassCastException: com.vaadin.server.communication.AtmospherePushConnection cannot be cast to com.github.mcollovati.vertx.vaadin.communication.SockJSPushConnection
	at com.github.mcollovati.vertx.vaadin.communication.SockJSPushHandler.getOpenedPushConnection(SockJSPushHandler.java:316)
	at com.github.mcollovati.vertx.vaadin.communication.SockJSPushHandler.callWithUi(SockJSPushHandler.java:281)
	at com.github.mcollovati.vertx.vaadin.communication.SockJSPushHandler.lambda$onConnect$2(SockJSPushHandler.java:189)
	at com.github.mcollovati.vertx.vaadin.communication.SockJSRoutingContext.lambda$next$1(SockJSPushHandler.java:624)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:339)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

**Comment by davidsowerby** [comment]
I need to provide some more info on this ... I'll give a bit more later

**Comment by mcollovati** [comment]
With Vaadin 8 `SockJSPushConnection` must be set manually

```
    @Override
    protected void init(VaadinRequest vaadinRequest) {
        setPushConnection(new SockJSPushConnection(this));
        ....
    }
```

Remember also that `setPushConnection` must be call also after `PushConfiguration.setPushMode(..)` is invoked.

In Vaadin Flow I've got a PR merged that allows to inject a `PushConnectionFactory` into `PushConfiguration` through `ServiceLoader` mechanism in order to have it done automatically.

**Comment by davidsowerby** [comment]
Thanks, applied changes in Krail 0.16.7.0 to fix this
