### ISSUE TITLE
Add support for vaadin 12.x

### ISSUE THREAD

**Issue by mcollovati** [mcollovati/vertx-vaadin#20]
`vertx-vaadin-flow` does not currently work with Vaadin 12.x due to missing of PWA related stuff implementation

**Comment by janderan** [comment]
also not starting after deploying ui verticle with vaadin version 13 & 14:

`[INFO] java.lang.AbstractMethodError: com.vaadin.flow.server.VaadinService.getRouteRegistry()Lcom/vaadin/flow/server/RouteRegistry;
[INFO] 	at com.vaadin.flow.server.VaadinService.init(VaadinService.java:259)
[INFO] 	at com.github.mcollovati.vertx.vaadin.VertxVaadin.<init>(VertxVaadin.java:102)
[INFO] 	at com.github.mcollovati.vertx.vaadin.VertxVaadin.<init>(VertxVaadin.java:120)
[INFO] 	at com.github.mcollovati.vertx.vaadin.VertxVaadin.create(VertxVaadin.java:308)
[INFO] 	at com.github.mcollovati.vertx.vaadin.VaadinVerticle.createVertxVaadin(VaadinVerticle.java:134)
[INFO] 	at com.github.mcollovati.vertx.vaadin.VaadinVerticle.start(VaadinVerticle.java:105)
[INFO] 	at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$8(DeploymentManager.java:491)
[INFO] 	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:339)
[INFO] 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
[INFO] 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
[INFO] 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
[INFO] 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
[INFO] 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[INFO] 	at java.lang.Thread.run(Thread.java:748)
[INFO] May 10, 2019 3:53:24 PM io.vertx.core.impl.launcher.commands.VertxIsolatedDeployer
[INFO] SEVERE: Failed in deploying verticle
[INFO] java.lang.AbstractMethodError: com.vaadin.flow.server.VaadinService.getRouteRegistry()Lcom/vaadin/flow/server/RouteRegistry;
[INFO] 	at com.vaadin.flow.server.VaadinService.init(VaadinService.java:259)
[INFO] 	at com.github.mcollovati.vertx.vaadin.VertxVaadin.<init>(VertxVaadin.java:102)
[INFO] 	at com.github.mcollovati.vertx.vaadin.VertxVaadin.<init>(VertxVaadin.java:120)
[INFO] 	at com.github.mcollovati.vertx.vaadin.VertxVaadin.create(VertxVaadin.java:308)
[INFO] 	at com.github.mcollovati.vertx.vaadin.VaadinVerticle.createVertxVaadin(VaadinVerticle.java:134)
[INFO] 	at com.github.mcollovati.vertx.vaadin.VaadinVerticle.start(VaadinVerticle.java:105)
[INFO] 	at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$8(DeploymentManager.java:491)
[INFO] 	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:339)
[INFO] 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
[INFO] 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
[INFO] 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
[INFO] 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
[INFO] 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[INFO] 	at java.lang.Thread.run(Thread.java:748)
[INFO] 
[INFO] java.lang.AbstractMethodError: com.vaadin.flow.server.VaadinService.getRouteRegistry()Lcom/vaadin/flow/server/RouteRegistry;
[INFO] 	at com.vaadin.flow.server.VaadinService.init(VaadinService.java:259)
[INFO] 	at com.github.mcollovati.vertx.vaadin.VertxVaadin.<init>(VertxVaadin.java:102)
[INFO] 	at com.github.mcollovati.vertx.vaadin.VertxVaadin.<init>(VertxVaadin.java:120)
[INFO] 	at com.github.mcollovati.vertx.vaadin.VertxVaadin.create(VertxVaadin.java:308)
[INFO] 	at com.github.mcollovati.vertx.vaadin.VaadinVerticle.createVertxVaadin(VaadinVerticle.java:134)
[INFO] 	at com.github.mcollovati.vertx.vaadin.VaadinVerticle.start(VaadinVerticle.java:105)
[INFO] 	at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$8(DeploymentManager.java:491)
[INFO] 	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:339)
[INFO] 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
[INFO] 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
[INFO] 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
[INFO] 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
[INFO] 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[INFO] 	at java.lang.Thread.run(Thread.java:748)`

**Comment by mcollovati** [comment]
Versions for Vaadin 12 and 13 are released; support for 14 is on development.

**Comment by janderan** [comment]
12 & 13 are working with a sample application.
i tried 14 and got:
`java.lang.NoClassDefFoundError: com/vaadin/flow/server/VaadinContext
	at com.github.mcollovati.vertx.vaadin.VertxVaadin.createVaadinService(VertxVaadin.java:171)
	at com.github.mcollovati.vertx.vaadin.VertxVaadin.<init>(VertxVaadin.java:100)
	at com.github.mcollovati.vertx.vaadin.VertxVaadin.<init>(VertxVaadin.java:124)
	at com.github.mcollovati.vertx.vaadin.VertxVaadin.create(VertxVaadin.java:316)
	at com.github.mcollovati.vertx.vaadin.VaadinVerticle.createVertxVaadin(VaadinVerticle.java:140)
	at com.github.mcollovati.vertx.vaadin.VaadinVerticle.start(VaadinVerticle.java:111)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$8(DeploymentManager.java:491)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:339)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: com.vaadin.flow.server.VaadinContext
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 14 more
Jun 13, 2019 3:11:15 PM io.vertx.core.impl.launcher.commands.VertxIsolatedDeployer
SEVERE: Failed in deploying verticle
java.lang.NoClassDefFoundError: com/vaadin/flow/server/VaadinContext
	at com.github.mcollovati.vertx.vaadin.VertxVaadin.createVaadinService(VertxVaadin.java:171)
	at com.github.mcollovati.vertx.vaadin.VertxVaadin.<init>(VertxVaadin.java:100)
	at com.github.mcollovati.vertx.vaadin.VertxVaadin.<init>(VertxVaadin.java:124)
	at com.github.mcollovati.vertx.vaadin.VertxVaadin.create(VertxVaadin.java:316)
	at com.github.mcollovati.vertx.vaadin.VaadinVerticle.createVertxVaadin(VaadinVerticle.java:140)
	at com.github.mcollovati.vertx.vaadin.VaadinVerticle.start(VaadinVerticle.java:111)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$8(DeploymentManager.java:491)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:339)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: com.vaadin.flow.server.VaadinContext
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 14 more

java.lang.NoClassDefFoundError: com/vaadin/flow/server/VaadinContext
	at com.github.mcollovati.vertx.vaadin.VertxVaadin.createVaadinService(VertxVaadin.java:171)
	at com.github.mcollovati.vertx.vaadin.VertxVaadin.<init>(VertxVaadin.java:100)
	at com.github.mcollovati.vertx.vaadin.VertxVaadin.<init>(VertxVaadin.java:124)
	at com.github.mcollovati.vertx.vaadin.VertxVaadin.create(VertxVaadin.java:316)
	at com.github.mcollovati.vertx.vaadin.VaadinVerticle.createVertxVaadin(VaadinVerticle.java:140)
	at com.github.mcollovati.vertx.vaadin.VaadinVerticle.start(VaadinVerticle.java:111)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$8(DeploymentManager.java:491)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:339)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: com.vaadin.flow.server.VaadinContext
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 14 more`

fixed it with replacing versions in vertx-vaadin/pom.xml:
`
        <vaadin.platform.version>14.0.0.beta3</vaadin.platform.version>
        <vaadin.flow.version>2.0.0.rc3</vaadin.flow.version>
`

hope this helps.
