### ISSUE TITLE
StackOverflowError when invoking route with parameters directly

### ISSUE THREAD

**Issue by mcollovati** [mcollovati/vertx-vaadin#22]
```
[INFO] SEVERE: Unexpected exception in route
[INFO] java.lang.StackOverflowError
[INFO]  at java.io.UnixFileSystem.getBooleanAttributes0(Native Method)
[INFO]  at java.io.UnixFileSystem.getBooleanAttributes(UnixFileSystem.java:242)
[INFO]  at java.io.File.exists(File.java:819)
[INFO]  at sun.misc.URLClassPath$FileLoader.getResource(URLClassPath.java:1334)
[INFO]  at sun.misc.URLClassPath.getResource(URLClassPath.java:249)
[INFO]  at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
[INFO]  at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
[INFO]  at java.security.AccessController.doPrivileged(Native Method)
[INFO]  at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
[INFO]  at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[INFO]  at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
[INFO]  at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[INFO]  at org.slf4j.impl.SimpleLogger.formatAndLog(SimpleLogger.java:354)
[INFO]  at org.slf4j.impl.SimpleLogger.error(SimpleLogger.java:580)
[INFO]  at com.vaadin.flow.router.InternalServerError.reportException(InternalServerError.java:96)
[INFO]  at com.vaadin.flow.router.InternalServerError.setErrorParameter(InternalServerError.java:61)
[INFO]  at com.vaadin.flow.router.internal.ErrorStateRenderer.notifyNavigationTarget(ErrorStateRenderer.java:60)
[INFO]  at com.vaadin.flow.router.internal.AbstractNavigationStateRenderer.handle(AbstractNavigationStateRenderer.java:181)
[INFO]  at com.vaadin.flow.router.internal.ErrorStateRenderer.handle(ErrorStateRenderer.java:49)
[INFO]  at com.vaadin.flow.router.Router.handleExceptionNavigation(Router.java:240)
[INFO]  at com.vaadin.flow.router.Router.navigate(Router.java:175)
[INFO]  at com.vaadin.flow.component.UI.navigate(UI.java:790)
[INFO]  at com.vaadin.flow.component.UI.navigate(UI.java:753)
[INFO]  at com.vaadin.flow.component.UI.navigate(UI.java:736)
[INFO]  at com.github.mcollovati.vertxvaadin.flowdemo.crud.SampleCrudLogic.setFragmentParameter(SampleCrudLogic.java:53)
[INFO]  at com.github.mcollovati.vertxvaadin.flowdemo.crud.SampleCrudLogic.newProduct(SampleCrudLogic.java:106)
[INFO]  at com.github.mcollovati.vertxvaadin.flowdemo.crud.SampleCrudLogic.enter(SampleCrudLogic.java:59)
[INFO]  at com.github.mcollovati.vertxvaadin.flowdemo.crud.SampleCrudView.setParameter(SampleCrudView.java:130)
[INFO]  at com.github.mcollovati.vertxvaadin.flowdemo.crud.SampleCrudView.setParameter(SampleCrudView.java:24)
[INFO]  at com.vaadin.flow.router.internal.NavigationStateRenderer.notifyNavigationTarget(NavigationStateRenderer.java:87)
[INFO]  at com.vaadin.flow.router.internal.AbstractNavigationStateRenderer.handle(AbstractNavigationStateRenderer.java:181)
[INFO]  at com.vaadin.flow.router.Router.handleNavigation(Router.java:202)
[INFO]  at com.vaadin.flow.router.Router.navigate(Router.java:173)
[INFO]  at com.vaadin.flow.component.UI.navigate(UI.java:790)
[INFO]  at com.vaadin.flow.component.UI.navigate(UI.java:753)
[INFO]  at com.vaadin.flow.component.UI.navigate(UI.java:736)
[INFO]  at com.github.mcollovati.vertxvaadin.flowdemo.crud.SampleCrudLogic.setFragmentParameter(SampleCrudLogic.java:53)
[INFO]  at com.github.mcollovati.vertxvaadin.flowdemo.crud.SampleCrudLogic.newProduct(SampleCrudLogic.java:106)
[INFO]  at com.github.mcollovati.vertxvaadin.flowdemo.crud.SampleCrudLogic.enter(SampleCrudLogic.java:59)
[INFO]  at com.github.mcollovati.vertxvaadin.flowdemo.crud.SampleCrudView.setParameter(SampleCrudView.java:130)
[INFO]  at com.github.mcollovati.vertxvaadin.flowdemo.crud.SampleCrudView.setParameter(SampleCrudView.java:24)
[INFO]  at com.vaadin.flow.router.internal.NavigationStateRenderer.notifyNavigationTarget(NavigationStateRenderer.java:87)
[INFO]  at com.vaadin.flow.router.internal.AbstractNavigationStateRenderer.handle(AbstractNavigationStateRenderer.java:181)
[INFO]  at com.vaadin.flow.router.Router.handleNavigation(Router.java:202)
[INFO]  at com.vaadin.flow.router.Router.navigate(Router.java:173)
[INFO]  at com.vaadin.flow.component.UI.navigate(UI.java:790)
[INFO]  at com.vaadin.flow.component.UI.navigate(UI.java:753)
[INFO]  at com.vaadin.flow.component.UI.navigate(UI.java:736)
[INFO]  at com.github.mcollovati.vertxvaadin.flowdemo.crud.SampleCrudLogic.setFragmentParameter(SampleCrudLogic.java:53)
[INFO]  at com.github.mcollovati.vertxvaadin.flowdemo.crud.SampleCrudLogic.newProduct(SampleCrudLogic.java:106)
[INFO]  at com.github.mcollovati.vertxvaadin.flowdemo.crud.SampleCrudLogic.enter(SampleCrudLogic.java:59)
[INFO]  at com.github.mcollovati.vertxvaadin.flowdemo.crud.SampleCrudView.setParameter(SampleCrudView.java:130)
[INFO]  at com.github.mcollovati.vertxvaadin.flowdemo.crud.SampleCrudView.setParameter(SampleCrudView.java:24)
[INFO]  at com.vaadin.flow.router.internal.NavigationStateRenderer.notifyNavigationTarget(NavigationStateRenderer.java:87)
[INFO]  at com.vaadin.flow.router.internal.AbstractNavigationStateRenderer.handle(AbstractNavigationStateRenderer.java:181)
[INFO]  at com.vaadin.flow.router.Router.handleNavigation(Router.java:202)
[INFO]  at com.vaadin.flow.router.Router.navigate(Router.java:173)
[INFO]  at com.vaadin.flow.component.UI.navigate(UI.java:790)
[INFO]  at com.vaadin.flow.component.UI.navigate(UI.java:753)
[INFO]  at com.vaadin.flow.component.UI.navigate(UI.java:736)
[INFO]  at com.github.mcollovati.vertxvaadin.flowdemo.crud.SampleCrudLogic.setFragmentParameter(SampleCrudLogic.java:53)
[INFO]  at com.github.mcollovati.vertxvaadin.flowdemo.crud.SampleCrudLogic.newProduct(SampleCrudLogic.java:106)
[INFO]  at com.github.mcollovati.vertxvaadin.flowdemo.crud.SampleCrudLogic.enter(SampleCrudLogic.java:59)
[INFO]  at com.github.mcollovati.vertxvaadin.flowdemo.crud.SampleCrudView.setParameter(SampleCrudView.java:130)
[INFO]  at com.github.mcollovati.vertxvaadin.flowdemo.crud.SampleCrudView.setParameter(SampleCrudView.java:24)
[INFO]  at com.vaadin.flow.router.internal.NavigationStateRenderer.notifyNavigationTarget(NavigationStateRenderer.java:87)
[INFO]  at com.vaadin.flow.router.internal.AbstractNavigationStateRenderer.handle(AbstractNavigationStateRenderer.java:181)
[INFO]  at com.vaadin.flow.router.Router.handleNavigation(Router.java:202)
[INFO]  at com.vaadin.flow.router.Router.navigate(Router.java:173)
[INFO]  at com.vaadin.flow.component.UI.navigate(UI.java:790)
[INFO]  at com.vaadin.flow.component.UI.navigate(UI.java:753)
[INFO]  at com.vaadin.flow.component.UI.navigate(UI.java:736)
[INFO]  at com.github.mcollovati.vertxvaadin.flowdemo.crud.SampleCrudLogic.setFragmentParameter(SampleCrudLogic.java:53)
[INFO]  at com.github.mcollovati.vertxvaadin.flowdemo.crud.SampleCrudLogic.newProduct(SampleCrudLogic.java:106)
[INFO]  at com.github.mcollovati.vertxvaadin.flowdemo.crud.SampleCrudLogic.enter(SampleCrudLogic.java:59)
[INFO]  at com.github.mcollovati.vertxvaadin.flowdemo.crud.SampleCrudView.setParameter(SampleCrudView.java:130)
[INFO]  at com.github.mcollovati.vertxvaadin.flowdemo.crud.SampleCrudView.setParameter(SampleCrudView.java:24)
[INFO]  at com.vaadin.flow.router.internal.NavigationStateRenderer.notifyNavigationTarget(NavigationStateRenderer.java:87)
[INFO]  at com.vaadin.flow.router.internal.AbstractNavigationStateRenderer.handle(AbstractNavigationStateRenderer.java:181)
```

**Comment by mcollovati** [comment]
Bug is on bookstore app; same error running on Jetty
