### ISSUE TITLE
SharedDataSessionImpl does not support Serializable

### ISSUE THREAD

**Issue by mcollovati** [mcollovati/vertx-vaadin#28]
`SharedDataSessionImpl` introduced in 3.6.0 in place of  `SessionImpl` does no more handle object implementing `Serializable`

**Comment by janderan** [comment]
will this be fixed? i'm using Vertx 3.8.0, Vaadin 14.0.0.rc7 and Vertx Vaadin Flow 14.0.0-SNAPSHOT

`ERROR 2019-07-31 14:19:38,093: Failed to store session ( io.vertx.ext.web.handler.impl.SessionHandlerImpl.lambda$null$5(SessionHandlerImpl.java:253)) [vert.x-eventloop-thread-1]  []
com.hazelcast.nio.serialization.HazelcastSerializationException: Failed to serialize 'io.vertx.spi.cluster.hazelcast.impl.ConversionUtils$DataSerializableHolder'
	at com.hazelcast.internal.serialization.impl.SerializationUtil.handleSerializeException(SerializationUtil.java:75) ~[hazelcast-3.10.5.jar:3.10.5]
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toBytes(AbstractSerializationService.java:157) ~[hazelcast-3.10.5.jar:3.10.5]
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toBytes(AbstractSerializationService.java:133) ~[hazelcast-3.10.5.jar:3.10.5]
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toData(AbstractSerializationService.java:118) ~[hazelcast-3.10.5.jar:3.10.5]
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toData(AbstractSerializationService.java:106) ~[hazelcast-3.10.5.jar:3.10.5]
	at com.hazelcast.spi.impl.NodeEngineImpl.toData(NodeEngineImpl.java:317) ~[hazelcast-3.10.5.jar:3.10.5]
	at com.hazelcast.spi.AbstractDistributedObject.toData(AbstractDistributedObject.java:68) ~[hazelcast-3.10.5.jar:3.10.5]
	at com.hazelcast.map.impl.proxy.MapProxyImpl.set(MapProxyImpl.java:197) ~[hazelcast-3.10.5.jar:3.10.5]
	at io.vertx.spi.cluster.hazelcast.impl.HazelcastAsyncMap.lambda$put$3(HazelcastAsyncMap.java:75) ~[vertx-hazelcast-3.8.0.jar:3.8.0]
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:316) ~[vertx-core-3.8.0.jar:3.8.0]
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76) ~[vertx-core-3.8.0.jar:3.8.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_181]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.34.Final.jar:4.1.34.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.IllegalStateException: Invalid type for data in session: class com.vaadin.flow.server.VaadinSession
	at io.vertx.ext.web.sstore.impl.SharedDataSessionImpl.writeDataToBuffer(SharedDataSessionImpl.java:144) ~[vertx-web-3.8.0.jar:3.8.0]
	at io.vertx.ext.web.sstore.impl.SharedDataSessionImpl.writeToBuffer(SharedDataSessionImpl.java:76) ~[vertx-web-3.8.0.jar:3.8.0]
	at io.vertx.spi.cluster.hazelcast.impl.ConversionUtils$DataSerializableHolder.writeData(ConversionUtils.java:49) ~[vertx-hazelcast-3.8.0.jar:3.8.0]
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.write(DataSerializableSerializer.java:244) ~[hazelcast-3.10.5.jar:3.10.5]
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.write(DataSerializableSerializer.java:51) ~[hazelcast-3.10.5.jar:3.10.5]
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.write(StreamSerializerAdapter.java:43) ~[hazelcast-3.10.5.jar:3.10.5]
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toBytes(AbstractSerializationService.java:154) ~[hazelcast-3.10.5.jar:3.10.5]
	... 13 more
`

**Comment by mcollovati** [comment]
I'm working on this issue;  to fix it I had to implement custom serialisation for non primitive e non ClusterSerializable object.
This seems to work, but some Vaadin component relies on `UI.current()` or similar constructs on component constructors (directly or not), so deserialisation sometimes fails when using clustered session; using local session seems to work fine.
I can publish a snapshot version of the current work if you want to try it

**Comment by mcollovati** [comment]
I've published a snapshot that adds support for `Serializable` objects.
Unfortunately it seems that some Vaadin components does not deserialize correctly when attached to a `VaadinSession` through `UI`.

I've got errors such the following one when running book store example 
```
Caused by: java.lang.ClassCastException: java.lang.invoke.SerializedLambda cannot be cast to com.vaadin.flow.function.SerializableConsumer
	at com.vaadin.flow.data.provider.AbstractDataProvider.$deserializeLambda$(AbstractDataProvider.java:41)
	... 494 more
``` 

A cause may be circular references in object graph: https://stackoverflow.com/a/18647941/5612275

**Comment by mcollovati** [comment]
Opened an issues on Vaadin flow for AbstractDataProvider serialization issue

**Comment by mcollovati** [comment]
AbstractDataProvider serialization has been fixed in Vaadin Flow
