### ISSUE TITLE
Vite not working because of VaadinServletContext explicit cast

### ISSUE THREAD

**Issue by mcollovati** [mcollovati/vertx-vaadin#70]
ViteHandler has an explicit cast to `VaadinServletContext` preventing it from working within vertx-vaadin

```
Caused by: java.lang.ClassCastException: class com.github.mcollovati.vertx.vaadin.VertxVaadinContext cannot be cast to class com.vaadin.flow.server.VaadinServletContext (com.github.mcollovati.vertx.vaadin.VertxVaadinContext and com.vaadin.flow.server.VaadinServletContext are in unnamed module of loader 'app')
	at com.vaadin.base.devserver.ViteHandler.getContextPath(ViteHandler.java:150)
	at com.vaadin.base.devserver.ViteHandler.getServerStartupCommand(ViteHandler.java:85)
	at com.vaadin.base.devserver.AbstractDevServerRunner.doStartDevServer(AbstractDevServerRunner.java:354)
	at com.vaadin.base.devserver.AbstractDevServerRunner.doStartDevModeServer(AbstractDevServerRunner.java:215)
	at com.vaadin.base.devserver.AbstractDevServerRunner.runOnFutureComplete(AbstractDevServerRunner.java:171)
	at com.vaadin.base.devserver.AbstractDevServerRunner.lambda$new$0(AbstractDevServerRunner.java:162)
```

**Comment by mcollovati** [comment]
Fixed by 718c68d3ced3eccceda2ac241f866e605da7d234
